/// Flutter icons VeusaxIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  VeusaxIcons
///      fonts:
///       - asset: fonts/VeusaxIcons.ttf
///
/// 
///
library;
import 'package:flutter/widgets.dart';

class VeusaxIcons {
  VeusaxIcons._();

  static const _kFontFam = 'VeusaxIcons';
  static const String? _kFontPkg = null;

  static const IconData location = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
